#!/usr/bin/python3

import pathlib
import subprocess
import logging
import json

# output_file = pathlib.Path.home().joinpath(".config", "i3", "config")
output_file = pathlib.Path("./output_config.i3")

# Create parent directories if they don't exist
output_file.parent.mkdir(parents=True, exist_ok=True)

# Write to the file
with open(output_file, "w") as f:
    # Autogenerated Warning
    f.write("# WARNING: This file is autogenerated. Do not modify directly.\n\n")

    # Append base i3 config (has to be first in the sequence because it contains all variable definitions)
    with open("base_config.i3", "r") as base_config:
        f.write(base_config.read())
    
    # Append all modules
    for subfolder in pathlib.Path("modules").iterdir():
        if subfolder.is_dir():  # Check if it's a directory
            subfolder_name = subfolder.name
        
            # Find all .i3 config files
            for config_file in subfolder.iterdir():
                if config_file.is_file() and config_file.suffix == ".i3":
                    section_header = f"""\n\n\n############################################################\n# {subfolder_name}/{config_file.name}\n############################################################\n"""
                    f.write(section_header)
                    with config_file.open("r") as i3_config:
                        f.write(i3_config.read())

            # Read the contents of dependencies.json
            dependencies_path = subfolder / 'dependencies.json'
            if dependencies_path.exists():
                with dependencies_path.open('r') as json_file:
                    dependencies_contents = json.load(json_file)
                    # print(f"Contents of {subfolder_name}/dependencies.json:")
                    # print(dependencies_contents)
            else:
                logging.warning(f"{dependencies_path} does not exist.")

# Reload
subprocess.run(["i3-msg", "reload"])