#!/bin/bash

# Config vars
CONFIG_DIR_PATH="./i3"
OUTPUT_DIR_PATH="$HOME/.config/i3"
OUTPUT_PATH=$OUTPUT_DIR_PATH/config

# Create directories if they don't already exist
mkdir -p $OUTPUT_DIR_PATH

# Overwrite existing content
echo -e "# WARNING: This file is autogenerated. Do not modify directly.\n\n" > $OUTPUT_PATH

# Append base i3 config (has to be first in the sequence because it contains all variable definitions)
cat $CONFIG_DIR_PATH/base >> $OUTPUT_PATH

# Append universal i3 config
for i in $CONFIG_DIR_PATH/universal/*; do
  {
    cat  "$i"
    echo -e "\n\n\n"
  } >> $OUTPUT_PATH
done

# Append local i3 config (make sure to verify local config manually beforehand)
for i in $CONFIG_DIR_PATH/local/*; do
  {
    cat  "$i"
    echo -e "\n\n\n"
  } >> $OUTPUT_PATH
done

# Reload
# i3msg reload
swaymsg reload