#!/bin/bash

# Define paths
OUTPUT_FILE="$HOME/.config/i3/config"
SCRIPTS_DIR="$HOME/.config/i3/scripts" # has to match config var in base_config.i3
BASE_CONFIG="base_config.i3"
MODULES_DIR="modules"

# Create parent directories if they don't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"
mkdir -p "$SCRIPTS_DIR"

# Write the autogenerated warning and base configuration to the output file
{
    echo "# WARNING: This file is autogenerated. Do not modify directly."
    echo
    cat "$BASE_CONFIG"
} > "$OUTPUT_FILE"

# Loop through each subdirectory in the modules folder
for SUBFOLDER in "$MODULES_DIR"/*; do
    if [ -d "$SUBFOLDER" ]; then
        SUBFOLDER_NAME=$(basename "$SUBFOLDER")

        # ========= i3 config files =========
        for CONFIG_FILE in "$SUBFOLDER"/*.i3; do
            if [ -f "$CONFIG_FILE" ]; then
                # Write the section header to the output file
                {
                    echo
                    echo "############################################################"
                    echo "# ${SUBFOLDER_NAME}/$(basename "$CONFIG_FILE")"
                    echo "############################################################"
                    cat "$CONFIG_FILE"
                    echo
                } >> "$OUTPUT_FILE"
            fi
        done
        
        # ========= Shell scripts =========
        for SHELL_SCRIPT in "$SUBFOLDER"/*.sh; do
            if [ -f "$SHELL_SCRIPT" ] && file "$SHELL_SCRIPT" | grep -q 'Bourne-Again'; then
                # Make script executable
                chmod +x "$SHELL_SCRIPT"
                # Copy to user path
                cp "$SHELL_SCRIPT" "$SCRIPTS_DIR/"
            fi
        done

        # Check for dependencies.json and log its contents if it exists
        # DEPENDENCIES_JSON="$SUBFOLDER/dependencies.json"
        # if [ -f "$DEPENDENCIES_JSON" ]; then
        #     DEP_CONTENTS=$(cat "$DEPENDENCIES_JSON")
        #     echo "Contents of ${SUBFOLDER_NAME}/dependencies.json:"
        #     echo "$DEP_CONTENTS"
        # else
        #     echo "Warning: $DEPENDENCIES_JSON does not exist."
        # fi
    fi
done

# Reload i3 configuration
i3-msg reload
