#!/bin/bash

# Define paths
OUTPUT_FILE="$HOME/.config/i3/config"
SCRIPTS_DIR="$HOME/.config/i3/scripts" # has to match config var in base_config.i3
BASE_CONFIG="./base_config.i3"

# Create parent directories if they don't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"
mkdir -p "$SCRIPTS_DIR"


# Write the autogenerated warning and base configuration to the output file
{
    echo "# WARNING: This file is autogenerated. Do not modify directly."
    echo
    cat "$BASE_CONFIG"
} > "$OUTPUT_FILE"

# Loop through each subdirectory in the modules folder
# for SUBFOLDER in ./modules/*; do
#     if [ -d "$SUBFOLDER" ]; then
#         SUBFOLDER_NAME=$(basename "$SUBFOLDER")
        # Check for dependencies.json and log its contents if it exists
        # DEPENDENCIES_JSON="$SUBFOLDER/dependencies.json"
        # if [ -f "$DEPENDENCIES_JSON" ]; then
        #     DEP_CONTENTS=$(cat "$DEPENDENCIES_JSON")
        #     echo "Contents of ${SUBFOLDER_NAME}/dependencies.json:"
        #     echo "$DEP_CONTENTS"
        # else
        #     echo "Warning: $DEPENDENCIES_JSON does not exist."
        # fi
#     fi
# done

# Compile i3 configs
for CONFIG_FILE in ./modules/*/*.i3; do
    MODULE_NAME=$(basename "$(dirname "$CONFIG_FILE")")
    FILE_NAME=$(basename "$CONFIG_FILE")
    {
        echo
        echo "############################################################"
        echo "# ${MODULE_NAME}/$(basename "$FILE_NAME")"
        echo "############################################################"
        cat "$CONFIG_FILE"
        echo
    } >> "$OUTPUT_FILE"
done

# Install custom scripts
for SHELL_SCRIPT in ./modules/*/*.sh; do
    if [ -f "$SHELL_SCRIPT" ] && ! [[ "$(basename "$SHELL_SCRIPT")" = "install.sh" ]]; then
        chmod +x "$SHELL_SCRIPT"
        cp "$SHELL_SCRIPT" "$SCRIPTS_DIR/"
    fi
done

# Reload i3 configuration
i3-msg reload > /dev/null
if [ $? -eq 0 ]; then
    echo "i3 configuration reloaded successfully."
else
    echo "Failed to reload i3 configuration."
fi
