set -g default-shell /usr/bin/fish

# For LazyNvim colorscheme: https://www.reddit.com/r/neovim/comments/xbzewr/colorscheme_not_working_inside_of_tmux/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1
set -g default-terminal 'tmux-256color'
set -as terminal-features ',xterm*:RGB'
